SELECT E.Ename, E.JOB, D.DNAME FROM s15269.apbd.EMP E,
s15269.apbd.DEPT D 
WHERE E.DEPTNO = D.DEPTNO;


SELECT E.Ename, E.JOB, D.DNAME FROM s15269.apbd.EMP E, s15269.apbd.DEPT D WHERE E.DEPTNO = D.DEPTNO AND E.ENAME = "Asia"